version: "3"
services:
  nginx-server:
    image: nginx:latest
    container_name: nginxserver-1
    ports:
      - "8050:80"

  health-check:
    build: .
    container_name: healthchecker-1
    volumes:
      - ./logs:/logs
    depends_on:
      - nginx-server